### ISSUE TITLE
Clustering MS/MS spectra from multiple species

### ISSUE THREAD

**Issue by chinmayaNK22** [bittremieux/GLEAMS#4]
Hello,

I have installed the GLEAMS tool in one of my conda env. I am planning to check MS/MS clusters specific to data from different species. However, the general gleams command execution shows only embed and cluster options for mzML input files. It is not clear whether the embedding has to be done together for all the mzML files from all the species or it has to be done separately and clustered together at the "gleams cluster" step?.

Please help

Thanks,
Chinmaya

**Comment by bittremieux** [comment]
To process multiple files:
1. Provide peak files as input to `gleams embed`. This will embed all spectra in all of the peak files and export a single embeddings file. GLEAMS can take mzML, mzXML, and MGF files as input.
2. Use the embeddings file with `gleams cluster` to cluster the embeddings. The clustering functionality only takes a single embeddings file as input, hence, you should embed all of your files together in the previous step.
