### ISSUE TITLE
about MassIVE-KB  datasets

### ISSUE THREAD

**Issue by wuwo007** [bittremieux/GLEAMS#6]
Thanks for sharing this great work. I think GLEAMS is very helpful for processing the mass spectrum.  
However, when I am checking the datasets used in GLEAMS, I cannot find how to download the 30 million high-quality PSMs of the MassIVE-KB spectral library and 185 million PSMs of the identification results for the full MassIVE-KB dataset in the MassIVE web site. Could you kindly help me about how to find these data?
Looking forward to your reply.

**Comment by bittremieux** [comment]
I have now included instructions on how to collect all of the data used to train and process with GLEAMS in the [FAQ section of the README](https://github.com/bittremieux/GLEAMS#frequently-asked-questions).
