### ISSUE TITLE
Number of spectra in MGF vs embed file does not match

### ISSUE THREAD

**Issue by petercim** [bittremieux/GLEAMS#7]
Hi,

I have an MGF file with 10,067 spectra in it, but running `gleams embed` only returns embeddings for 1,663 of them. Any idea why?

**Comment by petercim** [comment]
Is my assumption that the loss is due to filtering (per parameters [here](https://github.com/bittremieux/GLEAMS/blob/master/gleams/config.py#L7)), correct?

**Comment by bittremieux** [comment]
Indeed, GLEAMS skips spectra with an unsupported precursor charge (should be between 2 and 5) or with too few peaks or limited mass range after preprocessing (see line 18–24 in the linked config file).

**Comment by petercim** [comment]
Thanks, Wout!
